# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_pyqt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1434, 829)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 800))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.System_value_groupbox = QtGui.QGroupBox(self.centralwidget)
        self.System_value_groupbox.setMinimumSize(QtCore.QSize(161, 590))
        self.System_value_groupbox.setMaximumSize(QtCore.QSize(161, 16777215))
        self.System_value_groupbox.setObjectName(
            _fromUtf8("System_value_groupbox"))
        self.gridLayout_13 = QtGui.QGridLayout(self.System_value_groupbox)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.acc_groupbox = QtGui.QGroupBox(self.System_value_groupbox)
        self.acc_groupbox.setMinimumSize(QtCore.QSize(141, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.acc_groupbox.setFont(font)
        self.acc_groupbox.setObjectName(_fromUtf8("acc_groupbox"))
        self.gridLayout_15 = QtGui.QGridLayout(self.acc_groupbox)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label = QtGui.QLabel(self.acc_groupbox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_15.addWidget(self.label, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.acc_groupbox)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_15.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.acc_groupbox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_15.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.acc_groupbox)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_15.addWidget(self.label_19, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.acc_groupbox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_15.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.acc_groupbox)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_15.addWidget(self.label_20, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.acc_groupbox)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_15.addWidget(self.label_21, 3, 0, 1, 1)
        self.ACC_value = QtGui.QLabel(self.acc_groupbox)
        self.ACC_value.setFrameShape(QtGui.QFrame.NoFrame)
        self.ACC_value.setFrameShadow(QtGui.QFrame.Raised)
        self.ACC_value.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_value.setObjectName(_fromUtf8("ACC_value"))
        self.gridLayout_15.addWidget(self.ACC_value, 3, 1, 1, 1)
        self.gridLayout_13.addWidget(self.acc_groupbox, 3, 0, 1, 1)
        self.bpm_groupbox = QtGui.QGroupBox(self.System_value_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bpm_groupbox.setFont(font)
        self.bpm_groupbox.setObjectName(_fromUtf8("bpm_groupbox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.bpm_groupbox)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_25 = QtGui.QLabel(self.bpm_groupbox)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 0, 0, 1, 1)
        self.BPM_value = QtGui.QLabel(self.bpm_groupbox)
        self.BPM_value.setFrameShape(QtGui.QFrame.NoFrame)
        self.BPM_value.setFrameShadow(QtGui.QFrame.Raised)
        self.BPM_value.setAlignment(QtCore.Qt.AlignCenter)
        self.BPM_value.setObjectName(_fromUtf8("BPM_value"))
        self.gridLayout_12.addWidget(self.BPM_value, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.bpm_groupbox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_12.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.bpm_groupbox)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_12.addWidget(self.label_26, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.bpm_groupbox)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_12.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.bpm_groupbox)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_12.addWidget(self.label_27, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.bpm_groupbox, 2, 0, 1, 1)
        self.ibi_groupbox = QtGui.QGroupBox(self.System_value_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ibi_groupbox.setFont(font)
        self.ibi_groupbox.setObjectName(_fromUtf8("ibi_groupbox"))
        self.gridLayout_14 = QtGui.QGridLayout(self.ibi_groupbox)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_24 = QtGui.QLabel(self.ibi_groupbox)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_14.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.ibi_groupbox)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_14.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.ibi_groupbox)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_14.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.ibi_groupbox)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_14.addWidget(self.label_11, 2, 1, 1, 1)
        self.IBI_value = QtGui.QLabel(self.ibi_groupbox)
        self.IBI_value.setFrameShape(QtGui.QFrame.NoFrame)
        self.IBI_value.setFrameShadow(QtGui.QFrame.Raised)
        self.IBI_value.setAlignment(QtCore.Qt.AlignCenter)
        self.IBI_value.setObjectName(_fromUtf8("IBI_value"))
        self.gridLayout_14.addWidget(self.IBI_value, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.ibi_groupbox)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_14.addWidget(self.label_22, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.ibi_groupbox, 1, 0, 1, 1)
        self.tmp_groupbox = QtGui.QGroupBox(self.System_value_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tmp_groupbox.setFont(font)
        self.tmp_groupbox.setObjectName(_fromUtf8("tmp_groupbox"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tmp_groupbox)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_3 = QtGui.QLabel(self.tmp_groupbox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_16.addWidget(self.label_3, 0, 0, 1, 1)
        self.TMP_value = QtGui.QLabel(self.tmp_groupbox)
        self.TMP_value.setFrameShape(QtGui.QFrame.NoFrame)
        self.TMP_value.setFrameShadow(QtGui.QFrame.Raised)
        self.TMP_value.setAlignment(QtCore.Qt.AlignCenter)
        self.TMP_value.setObjectName(_fromUtf8("TMP_value"))
        self.gridLayout_16.addWidget(self.TMP_value, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tmp_groupbox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_16.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tmp_groupbox)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_16.addWidget(self.label_15, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tmp_groupbox)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_16.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.tmp_groupbox)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_16.addWidget(self.label_17, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.tmp_groupbox, 4, 0, 1, 1)
        self.eda_groupbox = QtGui.QGroupBox(self.System_value_groupbox)
        self.eda_groupbox.setMaximumSize(QtCore.QSize(141, 107))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eda_groupbox.setFont(font)
        self.eda_groupbox.setObjectName(_fromUtf8("eda_groupbox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.eda_groupbox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.eda_groupbox)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.EDA_value_2 = QtGui.QLabel(self.eda_groupbox)
        self.EDA_value_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.EDA_value_2.setFrameShadow(QtGui.QFrame.Raised)
        self.EDA_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.EDA_value_2.setObjectName(_fromUtf8("EDA_value_2"))
        self.gridLayout_2.addWidget(self.EDA_value_2, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.eda_groupbox)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.eda_groupbox)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.eda_groupbox)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.eda_groupbox)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.eda_groupbox, 0, 0, 1, 1)
        self.event_groupbox = QtGui.QGroupBox(self.System_value_groupbox)
        self.event_groupbox.setMinimumSize(QtCore.QSize(141, 53))
        self.event_groupbox.setMaximumSize(QtCore.QSize(141, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.event_groupbox.setFont(font)
        self.event_groupbox.setObjectName(_fromUtf8("event_groupbox"))
        self.gridLayout_17 = QtGui.QGridLayout(self.event_groupbox)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.EVE_value = QtGui.QLabel(self.event_groupbox)
        self.EVE_value.setFrameShape(QtGui.QFrame.NoFrame)
        self.EVE_value.setAlignment(QtCore.Qt.AlignCenter)
        self.EVE_value.setObjectName(_fromUtf8("EVE_value"))
        self.gridLayout_17.addWidget(self.EVE_value, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.event_groupbox)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_17.addWidget(self.label_28, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.event_groupbox, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.System_value_groupbox, 0, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 220))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.eda_button = QtGui.QPushButton(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.eda_button.sizePolicy().hasHeightForWidth())
        self.eda_button.setSizePolicy(sizePolicy)
        self.eda_button.setObjectName(_fromUtf8("eda_button"))
        self.verticalLayout.addWidget(self.eda_button)
        self.bvp_button = QtGui.QPushButton(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.bvp_button.sizePolicy().hasHeightForWidth())
        self.bvp_button.setSizePolicy(sizePolicy)
        self.bvp_button.setObjectName(_fromUtf8("bvp_button"))
        self.verticalLayout.addWidget(self.bvp_button)
        self.ibi_button = QtGui.QPushButton(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ibi_button.sizePolicy().hasHeightForWidth())
        self.ibi_button.setSizePolicy(sizePolicy)
        self.ibi_button.setObjectName(_fromUtf8("ibi_button"))
        self.verticalLayout.addWidget(self.ibi_button)
        self.acc_button = QtGui.QPushButton(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.acc_button.sizePolicy().hasHeightForWidth())
        self.acc_button.setSizePolicy(sizePolicy)
        self.acc_button.setObjectName(_fromUtf8("acc_button"))
        self.verticalLayout.addWidget(self.acc_button)
        self.tmp_button = QtGui.QPushButton(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tmp_button.sizePolicy().hasHeightForWidth())
        self.tmp_button.setSizePolicy(sizePolicy)
        self.tmp_button.setObjectName(_fromUtf8("tmp_button"))
        self.verticalLayout.addWidget(self.tmp_button)
        self.event_button = QtGui.QPushButton(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.event_button.sizePolicy().hasHeightForWidth())
        self.event_button.setSizePolicy(sizePolicy)
        self.event_button.setObjectName(_fromUtf8("event_button"))
        self.verticalLayout.addWidget(self.event_button)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_11, 5, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_9.setMinimumSize(QtCore.QSize(200, 80))
        self.groupBox_9.setMaximumSize(QtCore.QSize(161, 71))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.semaforo_widget = QtGui.QWidget(self.groupBox_9)
        self.semaforo_widget.setMinimumSize(QtCore.QSize(20, 20))
        self.semaforo_widget.setMaximumSize(QtCore.QSize(50, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive,
                         QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled,
                         QtGui.QPalette.ToolTipText, brush)
        self.semaforo_widget.setPalette(palette)
        self.semaforo_widget.setAutoFillBackground(True)
        self.semaforo_widget.setObjectName(_fromUtf8("semaforo_widget"))
        self.gridLayout_9.addWidget(self.semaforo_widget, 0, 0, 1, 1)
        self.semaforo_label_msg = QtGui.QLabel(self.groupBox_9)
        self.semaforo_label_msg.setMinimumSize(QtCore.QSize(90, 0))
        self.semaforo_label_msg.setText(_fromUtf8(""))
        self.semaforo_label_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.semaforo_label_msg.setWordWrap(True)
        self.semaforo_label_msg.setObjectName(_fromUtf8("semaforo_label_msg"))
        self.gridLayout_9.addWidget(self.semaforo_label_msg, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_10.setMinimumSize(QtCore.QSize(200, 95))
        self.groupBox_10.setMaximumSize(QtCore.QSize(161, 111))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.start_button_record = QtGui.QPushButton(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.start_button_record.sizePolicy().hasHeightForWidth())
        self.start_button_record.setSizePolicy(sizePolicy)
        self.start_button_record.setObjectName(
            _fromUtf8("start_button_record"))
        self.gridLayout_7.addWidget(self.start_button_record, 0, 0, 1, 1)
        self.pause_button = QtGui.QPushButton(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pause_button.sizePolicy().hasHeightForWidth())
        self.pause_button.setSizePolicy(sizePolicy)
        self.pause_button.setObjectName(_fromUtf8("pause_button"))
        self.gridLayout_7.addWidget(self.pause_button, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_10, 3, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(200, 111))
        self.groupBox_8.setMaximumSize(QtCore.QSize(161, 111))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.connect_button = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.connect_button.sizePolicy().hasHeightForWidth())
        self.connect_button.setSizePolicy(sizePolicy)
        self.connect_button.setMinimumSize(QtCore.QSize(140, 25))
        self.connect_button.setObjectName(_fromUtf8("connect_button"))
        self.verticalLayout_2.addWidget(self.connect_button)
        self.status_button = QtGui.QPushButton(self.groupBox_8)
        self.status_button.setMinimumSize(QtCore.QSize(140, 25))
        self.status_button.setObjectName(_fromUtf8("status_button"))
        self.verticalLayout_2.addWidget(self.status_button)
        self.devices_button = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.devices_button.sizePolicy().hasHeightForWidth())
        self.devices_button.setSizePolicy(sizePolicy)
        self.devices_button.setMinimumSize(QtCore.QSize(140, 25))
        self.devices_button.setObjectName(_fromUtf8("devices_button"))
        self.verticalLayout_2.addWidget(self.devices_button)
        self.gridLayout_6.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.select_al_channels_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.select_al_channels_button.sizePolicy().hasHeightForWidth())
        self.select_al_channels_button.setSizePolicy(sizePolicy)
        self.select_al_channels_button.setObjectName(
            _fromUtf8("select_al_channels_button"))
        self.gridLayout_11.addWidget(
            self.select_al_channels_button, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 4, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(
            QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 75))
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 60))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        self.label_29.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 0, 0, 1, 1)
        self.id_participante = QtGui.QPlainTextEdit(self.groupBox_4)
        self.id_participante.setMinimumSize(QtCore.QSize(140, 30))
        self.id_participante.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_participante.setFont(font)
        self.id_participante.setObjectName(_fromUtf8("id_participante"))
        self.gridLayout_3.addWidget(self.id_participante, 0, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.SYS_value = QtGui.QLabel(self.groupBox_3)
        self.SYS_value.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SYS_value.setFont(font)
        self.SYS_value.setObjectName(_fromUtf8("SYS_value"))
        self.gridLayout_4.addWidget(self.SYS_value, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 2)
        self.system_signal_layout = QtGui.QGroupBox(self.centralwidget)
        self.system_signal_layout.setMinimumSize(QtCore.QSize(0, 590))
        self.system_signal_layout.setObjectName(
            _fromUtf8("system_signal_layout"))
        self.gridLayout_8 = QtGui.QGridLayout(self.system_signal_layout)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.signal_layout = QtGui.QGridLayout()
        self.signal_layout.setSizeConstraint(
            QtGui.QLayout.SetDefaultConstraint)
        self.signal_layout.setObjectName(_fromUtf8("signal_layout"))
        self.gridLayout_8.addLayout(self.signal_layout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.system_signal_layout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1434, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSession = QtGui.QMenu(self.menubar)
        self.menuSession.setObjectName(_fromUtf8("menuSession"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_session = QtGui.QAction(MainWindow)
        self.actionNew_session.setObjectName(_fromUtf8("actionNew_session"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout_this_app = QtGui.QAction(MainWindow)
        self.actionAbout_this_app.setObjectName(
            _fromUtf8("actionAbout_this_app"))
        self.menuSession.addSeparator()
        self.menuSession.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout_this_app)
        self.menubar.addAction(self.menuSession.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Empatica 4. Data acquisition Window", None))
        self.System_value_groupbox.setTitle(_translate(
            "MainWindow", "Valores del sistema", None))
        self.acc_groupbox.setTitle(_translate(
            "MainWindow", "Acceleration", None))
        self.label.setText(_translate("MainWindow", "X Axis", None))
        self.label_18.setText(_translate("MainWindow", "N/A", None))
        self.label_2.setText(_translate("MainWindow", "Y Axis", None))
        self.label_19.setText(_translate("MainWindow", "N/A", None))
        self.label_4.setText(_translate("MainWindow", "Z Axis", None))
        self.label_20.setText(_translate("MainWindow", "N/A", None))
        self.label_21.setText(_translate("MainWindow", "Module", None))
        self.ACC_value.setText(_translate("MainWindow", "N/A", None))
        self.bpm_groupbox.setTitle(_translate(
            "MainWindow", "Beats Per Minute", None))
        self.label_25.setText(_translate("MainWindow", "Now", None))
        self.BPM_value.setText(_translate("MainWindow", "N/A", None))
        self.label_5.setText(_translate("MainWindow", "Max.", None))
        self.label_26.setText(_translate("MainWindow", "N/A", None))
        self.label_7.setText(_translate("MainWindow", "Min.", None))
        self.label_27.setText(_translate("MainWindow", "N/A", None))
        self.ibi_groupbox.setTitle(_translate(
            "MainWindow", "Inter-Beat Interval", None))
        self.label_24.setText(_translate("MainWindow", "Min", None))
        self.label_23.setText(_translate("MainWindow", "Max.", None))
        self.label_9.setText(_translate("MainWindow", "N/A", None))
        self.label_11.setText(_translate("MainWindow", "N/A", None))
        self.IBI_value.setText(_translate("MainWindow", "N/A", None))
        self.label_22.setText(_translate("MainWindow", "Now", None))
        self.tmp_groupbox.setTitle(_translate(
            "MainWindow", "Temperature", None))
        self.label_3.setText(_translate("MainWindow", "Now", None))
        self.TMP_value.setText(_translate("MainWindow", "N/A", None))
        self.label_6.setText(_translate("MainWindow", "Max.", None))
        self.label_15.setText(_translate("MainWindow", "N/A", None))
        self.label_8.setText(_translate("MainWindow", "Min.", None))
        self.label_17.setText(_translate("MainWindow", "N/A", None))
        self.eda_groupbox.setTitle(_translate(
            "MainWindow", "Electro-Dermal Activity", None))
        self.label_10.setText(_translate("MainWindow", "Now", None))
        self.EDA_value_2.setText(_translate("MainWindow", "N/A", None))
        self.label_12.setText(_translate("MainWindow", "Max.", None))
        self.label_13.setText(_translate("MainWindow", "N/A", None))
        self.label_14.setText(_translate("MainWindow", "Min. ", None))
        self.label_16.setText(_translate("MainWindow", "N/A", None))
        self.event_groupbox.setTitle(_translate("MainWindow", "Events", None))
        self.EVE_value.setText(_translate("MainWindow", "N/A", None))
        self.label_28.setText(_translate("MainWindow", "Value", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Capturador", None))
        self.groupBox_11.setTitle(_translate(
            "MainWindow", "Selecciona los canales", None))
        self.eda_button.setText(_translate("MainWindow", "EDA", None))
        self.bvp_button.setText(_translate("MainWindow", "BVP", None))
        self.ibi_button.setText(_translate("MainWindow", "I-B", None))
        self.acc_button.setText(_translate(
            "MainWindow", "Accelerometer", None))
        self.tmp_button.setText(_translate("MainWindow", "Temperature", None))
        self.event_button.setText(_translate("MainWindow", "Event", None))
        self.groupBox_9.setTitle(_translate(
            "MainWindow", "Estado del Sistema", None))
        self.groupBox_10.setTitle(_translate(
            "MainWindow", "Adquisición de datos", None))
        self.start_button_record.setText(
            _translate("MainWindow", "Start recording", None))
        self.pause_button.setText(_translate("MainWindow", "Pause", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Dispositivo", None))
        self.connect_button.setText(_translate("MainWindow", "Connect", None))
        self.status_button.setText(_translate("MainWindow", "Status", None))
        self.devices_button.setText(_translate(
            "MainWindow", "Devices connected", None))
        self.groupBox.setTitle(_translate(
            "MainWindow", "Todos los canales", None))
        self.select_al_channels_button.setText(
            _translate("MainWindow", "Select all channels", None))
        self.groupBox_4.setTitle(_translate(
            "MainWindow", "Participante", None))
        self.label_29.setText(_translate("MainWindow", "ID", None))
        self.groupBox_3.setTitle(_translate(
            "MainWindow", "Mensajes del sistema", None))
        self.SYS_value.setText(_translate("MainWindow", "N/A", None))
        self.system_signal_layout.setTitle(_translate(
            "MainWindow", "Señales fisiologicas", None))
        self.menuSession.setTitle(_translate("MainWindow", "Session", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionNew_session.setText(
            _translate("MainWindow", "New session", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout_this_app.setText(_translate(
            "MainWindow", "About this app....", None))
