# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Robert\Desktop\Empatica_Datos_Beta4\gui_pyqt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1434, 829)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.System_value_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.System_value_groupbox.setMinimumSize(QtCore.QSize(161, 590))
        self.System_value_groupbox.setMaximumSize(QtCore.QSize(161, 16777215))
        self.System_value_groupbox.setObjectName("System_value_groupbox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.System_value_groupbox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.acc_groupbox = QtWidgets.QGroupBox(self.System_value_groupbox)
        self.acc_groupbox.setMinimumSize(QtCore.QSize(141, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.acc_groupbox.setFont(font)
        self.acc_groupbox.setObjectName("acc_groupbox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.acc_groupbox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label = QtWidgets.QLabel(self.acc_groupbox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_15.addWidget(self.label, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.acc_groupbox)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.acc_groupbox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_15.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.acc_groupbox)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_15.addWidget(self.label_19, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.acc_groupbox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.acc_groupbox)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.acc_groupbox)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_15.addWidget(self.label_21, 3, 0, 1, 1)
        self.ACC_value = QtWidgets.QLabel(self.acc_groupbox)
        self.ACC_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ACC_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ACC_value.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_value.setObjectName("ACC_value")
        self.gridLayout_15.addWidget(self.ACC_value, 3, 1, 1, 1)
        self.gridLayout_13.addWidget(self.acc_groupbox, 3, 0, 1, 1)
        self.bpm_groupbox = QtWidgets.QGroupBox(self.System_value_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bpm_groupbox.setFont(font)
        self.bpm_groupbox.setObjectName("bpm_groupbox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.bpm_groupbox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_25 = QtWidgets.QLabel(self.bpm_groupbox)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 0, 0, 1, 1)
        self.BPM_value = QtWidgets.QLabel(self.bpm_groupbox)
        self.BPM_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BPM_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BPM_value.setAlignment(QtCore.Qt.AlignCenter)
        self.BPM_value.setObjectName("BPM_value")
        self.gridLayout_12.addWidget(self.BPM_value, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.bpm_groupbox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_12.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.bpm_groupbox)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.bpm_groupbox)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.bpm_groupbox)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.bpm_groupbox, 2, 0, 1, 1)
        self.ibi_groupbox = QtWidgets.QGroupBox(self.System_value_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ibi_groupbox.setFont(font)
        self.ibi_groupbox.setObjectName("ibi_groupbox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.ibi_groupbox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_24 = QtWidgets.QLabel(self.ibi_groupbox)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_14.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.ibi_groupbox)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_14.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.ibi_groupbox)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_14.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.ibi_groupbox)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_14.addWidget(self.label_11, 2, 1, 1, 1)
        self.IBI_value = QtWidgets.QLabel(self.ibi_groupbox)
        self.IBI_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IBI_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.IBI_value.setAlignment(QtCore.Qt.AlignCenter)
        self.IBI_value.setObjectName("IBI_value")
        self.gridLayout_14.addWidget(self.IBI_value, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.ibi_groupbox)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_14.addWidget(self.label_22, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.ibi_groupbox, 1, 0, 1, 1)
        self.tmp_groupbox = QtWidgets.QGroupBox(self.System_value_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tmp_groupbox.setFont(font)
        self.tmp_groupbox.setObjectName("tmp_groupbox")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tmp_groupbox)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_3 = QtWidgets.QLabel(self.tmp_groupbox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_16.addWidget(self.label_3, 0, 0, 1, 1)
        self.TMP_value = QtWidgets.QLabel(self.tmp_groupbox)
        self.TMP_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TMP_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TMP_value.setAlignment(QtCore.Qt.AlignCenter)
        self.TMP_value.setObjectName("TMP_value")
        self.gridLayout_16.addWidget(self.TMP_value, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tmp_groupbox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_16.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tmp_groupbox)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_16.addWidget(self.label_15, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tmp_groupbox)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_16.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tmp_groupbox)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_16.addWidget(self.label_17, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.tmp_groupbox, 4, 0, 1, 1)
        self.eda_groupbox = QtWidgets.QGroupBox(self.System_value_groupbox)
        self.eda_groupbox.setMaximumSize(QtCore.QSize(141, 107))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eda_groupbox.setFont(font)
        self.eda_groupbox.setObjectName("eda_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.eda_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.eda_groupbox)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.EDA_value_2 = QtWidgets.QLabel(self.eda_groupbox)
        self.EDA_value_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.EDA_value_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.EDA_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.EDA_value_2.setObjectName("EDA_value_2")
        self.gridLayout_2.addWidget(self.EDA_value_2, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.eda_groupbox)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.eda_groupbox)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.eda_groupbox)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.eda_groupbox)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 1, 1, 1)
        self.gridLayout_13.addWidget(self.eda_groupbox, 0, 0, 1, 1)
        self.event_groupbox = QtWidgets.QGroupBox(self.System_value_groupbox)
        self.event_groupbox.setMinimumSize(QtCore.QSize(141, 53))
        self.event_groupbox.setMaximumSize(QtCore.QSize(141, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.event_groupbox.setFont(font)
        self.event_groupbox.setObjectName("event_groupbox")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.event_groupbox)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.EVE_value = QtWidgets.QLabel(self.event_groupbox)
        self.EVE_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.EVE_value.setAlignment(QtCore.Qt.AlignCenter)
        self.EVE_value.setObjectName("EVE_value")
        self.gridLayout_17.addWidget(self.EVE_value, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.event_groupbox)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_17.addWidget(self.label_28, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.event_groupbox, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.System_value_groupbox, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 220))
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.eda_button = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eda_button.sizePolicy().hasHeightForWidth())
        self.eda_button.setSizePolicy(sizePolicy)
        self.eda_button.setObjectName("eda_button")
        self.verticalLayout.addWidget(self.eda_button)
        self.bvp_button = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bvp_button.sizePolicy().hasHeightForWidth())
        self.bvp_button.setSizePolicy(sizePolicy)
        self.bvp_button.setObjectName("bvp_button")
        self.verticalLayout.addWidget(self.bvp_button)
        self.ibi_button = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ibi_button.sizePolicy().hasHeightForWidth())
        self.ibi_button.setSizePolicy(sizePolicy)
        self.ibi_button.setObjectName("ibi_button")
        self.verticalLayout.addWidget(self.ibi_button)
        self.acc_button = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acc_button.sizePolicy().hasHeightForWidth())
        self.acc_button.setSizePolicy(sizePolicy)
        self.acc_button.setObjectName("acc_button")
        self.verticalLayout.addWidget(self.acc_button)
        self.tmp_button = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tmp_button.sizePolicy().hasHeightForWidth())
        self.tmp_button.setSizePolicy(sizePolicy)
        self.tmp_button.setObjectName("tmp_button")
        self.verticalLayout.addWidget(self.tmp_button)
        self.event_button = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_button.sizePolicy().hasHeightForWidth())
        self.event_button.setSizePolicy(sizePolicy)
        self.event_button.setObjectName("event_button")
        self.verticalLayout.addWidget(self.event_button)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_11, 5, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_9.setMinimumSize(QtCore.QSize(200, 80))
        self.groupBox_9.setMaximumSize(QtCore.QSize(161, 71))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.semaforo_widget = QtWidgets.QWidget(self.groupBox_9)
        self.semaforo_widget.setMinimumSize(QtCore.QSize(20, 20))
        self.semaforo_widget.setMaximumSize(QtCore.QSize(50, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 86, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.semaforo_widget.setPalette(palette)
        self.semaforo_widget.setAutoFillBackground(True)
        self.semaforo_widget.setObjectName("semaforo_widget")
        self.gridLayout_9.addWidget(self.semaforo_widget, 0, 0, 1, 1)
        self.semaforo_label_msg = QtWidgets.QLabel(self.groupBox_9)
        self.semaforo_label_msg.setMinimumSize(QtCore.QSize(90, 0))
        self.semaforo_label_msg.setText("")
        self.semaforo_label_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.semaforo_label_msg.setWordWrap(True)
        self.semaforo_label_msg.setObjectName("semaforo_label_msg")
        self.gridLayout_9.addWidget(self.semaforo_label_msg, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_10.setMinimumSize(QtCore.QSize(200, 95))
        self.groupBox_10.setMaximumSize(QtCore.QSize(161, 111))
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.start_button_record = QtWidgets.QPushButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button_record.sizePolicy().hasHeightForWidth())
        self.start_button_record.setSizePolicy(sizePolicy)
        self.start_button_record.setObjectName("start_button_record")
        self.gridLayout_7.addWidget(self.start_button_record, 0, 0, 1, 1)
        self.pause_button = QtWidgets.QPushButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_button.sizePolicy().hasHeightForWidth())
        self.pause_button.setSizePolicy(sizePolicy)
        self.pause_button.setObjectName("pause_button")
        self.gridLayout_7.addWidget(self.pause_button, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_10, 3, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(200, 111))
        self.groupBox_8.setMaximumSize(QtCore.QSize(161, 111))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.connect_button = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_button.sizePolicy().hasHeightForWidth())
        self.connect_button.setSizePolicy(sizePolicy)
        self.connect_button.setMinimumSize(QtCore.QSize(140, 25))
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_2.addWidget(self.connect_button)
        self.status_button = QtWidgets.QPushButton(self.groupBox_8)
        self.status_button.setMinimumSize(QtCore.QSize(140, 25))
        self.status_button.setObjectName("status_button")
        self.verticalLayout_2.addWidget(self.status_button)
        self.devices_button = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devices_button.sizePolicy().hasHeightForWidth())
        self.devices_button.setSizePolicy(sizePolicy)
        self.devices_button.setMinimumSize(QtCore.QSize(140, 25))
        self.devices_button.setObjectName("devices_button")
        self.verticalLayout_2.addWidget(self.devices_button)
        self.gridLayout_6.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.select_al_channels_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_al_channels_button.sizePolicy().hasHeightForWidth())
        self.select_al_channels_button.setSizePolicy(sizePolicy)
        self.select_al_channels_button.setObjectName("select_al_channels_button")
        self.gridLayout_11.addWidget(self.select_al_channels_button, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 4, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 75))
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 60))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 0, 1, 1)
        self.id_participant = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.id_participant.setMinimumSize(QtCore.QSize(140, 30))
        self.id_participant.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_participant.setFont(font)
        self.id_participant.setObjectName("id_participant")
        self.gridLayout_3.addWidget(self.id_participant, 0, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SYS_value = QtWidgets.QLabel(self.groupBox_3)
        self.SYS_value.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SYS_value.setFont(font)
        self.SYS_value.setObjectName("SYS_value")
        self.gridLayout_4.addWidget(self.SYS_value, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 2)
        self.system_signal_layout = QtWidgets.QGroupBox(self.centralwidget)
        self.system_signal_layout.setMinimumSize(QtCore.QSize(0, 590))
        self.system_signal_layout.setObjectName("system_signal_layout")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.system_signal_layout)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.signal_layout = QtWidgets.QGridLayout()
        self.signal_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.signal_layout.setObjectName("signal_layout")
        self.gridLayout_8.addLayout(self.signal_layout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.system_signal_layout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1434, 22))
        self.menubar.setObjectName("menubar")
        self.menuSession = QtWidgets.QMenu(self.menubar)
        self.menuSession.setObjectName("menuSession")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_session = QtWidgets.QAction(MainWindow)
        self.actionNew_session.setObjectName("actionNew_session")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_this_app = QtWidgets.QAction(MainWindow)
        self.actionAbout_this_app.setObjectName("actionAbout_this_app")
        self.menuSession.addSeparator()
        self.menuSession.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout_this_app)
        self.menubar.addAction(self.menuSession.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Empatica 4. Data acquisition Window"))
        self.System_value_groupbox.setTitle(_translate("MainWindow", "Valores del sistema"))
        self.acc_groupbox.setTitle(_translate("MainWindow", "Acceleration"))
        self.label.setText(_translate("MainWindow", "X Axis"))
        self.label_18.setText(_translate("MainWindow", "N/A"))
        self.label_2.setText(_translate("MainWindow", "Y Axis"))
        self.label_19.setText(_translate("MainWindow", "N/A"))
        self.label_4.setText(_translate("MainWindow", "Z Axis"))
        self.label_20.setText(_translate("MainWindow", "N/A"))
        self.label_21.setText(_translate("MainWindow", "Module"))
        self.ACC_value.setText(_translate("MainWindow", "N/A"))
        self.bpm_groupbox.setTitle(_translate("MainWindow", "Beats Per Minute"))
        self.label_25.setText(_translate("MainWindow", "Now"))
        self.BPM_value.setText(_translate("MainWindow", "N/A"))
        self.label_5.setText(_translate("MainWindow", "Max."))
        self.label_26.setText(_translate("MainWindow", "N/A"))
        self.label_7.setText(_translate("MainWindow", "Min."))
        self.label_27.setText(_translate("MainWindow", "N/A"))
        self.ibi_groupbox.setTitle(_translate("MainWindow", "Inter-Beat Interval"))
        self.label_24.setText(_translate("MainWindow", "Min"))
        self.label_23.setText(_translate("MainWindow", "Max."))
        self.label_9.setText(_translate("MainWindow", "N/A"))
        self.label_11.setText(_translate("MainWindow", "N/A"))
        self.IBI_value.setText(_translate("MainWindow", "N/A"))
        self.label_22.setText(_translate("MainWindow", "Now"))
        self.tmp_groupbox.setTitle(_translate("MainWindow", "Temperature"))
        self.label_3.setText(_translate("MainWindow", "Now"))
        self.TMP_value.setText(_translate("MainWindow", "N/A"))
        self.label_6.setText(_translate("MainWindow", "Max."))
        self.label_15.setText(_translate("MainWindow", "N/A"))
        self.label_8.setText(_translate("MainWindow", "Min."))
        self.label_17.setText(_translate("MainWindow", "N/A"))
        self.eda_groupbox.setTitle(_translate("MainWindow", "Electro-Dermal Activity"))
        self.label_10.setText(_translate("MainWindow", "Now"))
        self.EDA_value_2.setText(_translate("MainWindow", "N/A"))
        self.label_12.setText(_translate("MainWindow", "Max."))
        self.label_13.setText(_translate("MainWindow", "N/A"))
        self.label_14.setText(_translate("MainWindow", "Min. "))
        self.label_16.setText(_translate("MainWindow", "N/A"))
        self.event_groupbox.setTitle(_translate("MainWindow", "Events"))
        self.EVE_value.setText(_translate("MainWindow", "N/A"))
        self.label_28.setText(_translate("MainWindow", "Value"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Capturador"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Selecciona los canales"))
        self.eda_button.setText(_translate("MainWindow", "EDA"))
        self.bvp_button.setText(_translate("MainWindow", "BVP"))
        self.ibi_button.setText(_translate("MainWindow", "I-B"))
        self.acc_button.setText(_translate("MainWindow", "Accelerometer"))
        self.tmp_button.setText(_translate("MainWindow", "Temperature"))
        self.event_button.setText(_translate("MainWindow", "Event"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Estado del Sistema"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Adquisición de datos"))
        self.start_button_record.setText(_translate("MainWindow", "Start recording"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Dispositivo"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.status_button.setText(_translate("MainWindow", "Status"))
        self.devices_button.setText(_translate("MainWindow", "Devices connected"))
        self.groupBox.setTitle(_translate("MainWindow", "Todos los canales"))
        self.select_al_channels_button.setText(_translate("MainWindow", "Select all channels"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Participante"))
        self.label_29.setText(_translate("MainWindow", "ID"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Mensajes del sistema"))
        self.SYS_value.setText(_translate("MainWindow", "N/A"))
        self.system_signal_layout.setTitle(_translate("MainWindow", "Señales fisiologicas"))
        self.menuSession.setTitle(_translate("MainWindow", "Session"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionNew_session.setText(_translate("MainWindow", "New session"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout_this_app.setText(_translate("MainWindow", "About this app...."))

